/**
 * Public CDN URLs for portfolio media stored in Vercel Blob.
 * Regenerated by: npm run media:upload
 */
export const BLOB_HOST = "e8zjl9cczfol7u0a.public.blob.vercel-storage.com" as const

export const media = {
  "/academic-projects.png": "https://e8zjl9cczfol7u0a.public.blob.vercel-storage.com/portfolio/academic-projects.png",
  "/bookhub.png": "https://e8zjl9cczfol7u0a.public.blob.vercel-storage.com/portfolio/bookhub.png",
  "/earthwise.jpg": "https://e8zjl9cczfol7u0a.public.blob.vercel-storage.com/portfolio/earthwise.jpg",
  "/file-management.png": "https://e8zjl9cczfol7u0a.public.blob.vercel-storage.com/portfolio/file-management.png",
  "/fitness-booking.jpg": "https://e8zjl9cczfol7u0a.public.blob.vercel-storage.com/portfolio/fitness-booking.jpg",
  "/graphics-sowc.png": "https://e8zjl9cczfol7u0a.public.blob.vercel-storage.com/portfolio/graphics-sowc.png",
  "/honnette.png": "https://e8zjl9cczfol7u0a.public.blob.vercel-storage.com/portfolio/honnette.png",
  "/iarm.png": "https://e8zjl9cczfol7u0a.public.blob.vercel-storage.com/portfolio/iarm.png",
  "/innocent_photos.png": "https://e8zjl9cczfol7u0a.public.blob.vercel-storage.com/portfolio/innocent_photos.png",
  "/lbf.png": "https://e8zjl9cczfol7u0a.public.blob.vercel-storage.com/portfolio/lbf.png",
  "/mindsafi.png": "https://e8zjl9cczfol7u0a.public.blob.vercel-storage.com/portfolio/mindsafi.png",
  "/olearn.webp": "https://e8zjl9cczfol7u0a.public.blob.vercel-storage.com/portfolio/olearn.webp",
  "/patrick_byishimo.png": "https://e8zjl9cczfol7u0a.public.blob.vercel-storage.com/portfolio/patrick_byishimo.png",
  "/Patrick.png": "https://e8zjl9cczfol7u0a.public.blob.vercel-storage.com/portfolio/Patrick.png",
  "/PPEA.png": "https://e8zjl9cczfol7u0a.public.blob.vercel-storage.com/portfolio/PPEA.png",
  "/Prince.jpg": "https://e8zjl9cczfol7u0a.public.blob.vercel-storage.com/portfolio/Prince.jpg",
  "/Prince2.jpg": "https://e8zjl9cczfol7u0a.public.blob.vercel-storage.com/portfolio/Prince2.jpg",
  "/profile.PNG": "https://e8zjl9cczfol7u0a.public.blob.vercel-storage.com/portfolio/profile.PNG",
  "/sango.png": "https://e8zjl9cczfol7u0a.public.blob.vercel-storage.com/portfolio/sango.png",
  "/skillhub.png": "https://e8zjl9cczfol7u0a.public.blob.vercel-storage.com/portfolio/skillhub.png",
  "/Talent Bridge Africa.png": "https://e8zjl9cczfol7u0a.public.blob.vercel-storage.com/portfolio/Talent%20Bridge%20Africa.png",
  "/tekriders.png": "https://e8zjl9cczfol7u0a.public.blob.vercel-storage.com/portfolio/tekriders.png",
  "/rwoga.png": "https://e8zjl9cczfol7u0a.public.blob.vercel-storage.com/portfolio/rwoga.png",
  "/CSM.png": "https://e8zjl9cczfol7u0a.public.blob.vercel-storage.com/portfolio/CSM.png",
  "/FESL.png": "https://e8zjl9cczfol7u0a.public.blob.vercel-storage.com/portfolio/FESL.png"
} as const

export type MediaPath = keyof typeof media
